# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_mdl_wrappers", use_symbols = TRUE, package_name = "mdl")

#' @docType package
#' @usage NULL
#' @useDynLib mdl, .registration = TRUE
NULL

model_matrix <- function(data) .Call(wrap__model_matrix, data)


# nolint end
